### ISSUE TITLE
Compiled binary?

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [nehalem501/open-tgm#1]
Hi, can I download compiled binaries?
Because they are too old, setting up the building environments seems to be difficult.

**Comment by nehalem501** [comment]
The game is not finished, so this is why I haven't released any binary.
Also there still a lot of work to port the game to all the planned platforms.
You'd like a binary for which system ?

**Comment by tokumeiwokiboushimasu** [comment]
PlayStation 1 the most, but I want to play many platforms.

**Comment by nehalem501** [comment]
The PS1 port is virtually non-existent, the core of the game compiles for the PS1 but there isn't any input or graphics code written for it. It will get done some time in the future but I don't have a lot of time to spend on this project.
If you want to play a TGM clone on PC I might suggest Shiromino, Texmaster or Minote that are much more advanced than this work-in-progress game.

**Comment by tokumeiwokiboushimasu** [comment]
Ah, thanks for the reply.
I can wait ;-)
